name: build
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel build twine keyring keyrings.google-artifactregistry-auth

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '${{ secrets.GCLOUD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCLOUD_SERVICE_ACCOUNT }}'

    - name: Check Tag
      id: check_tag
      run: |
        if [[ ! '${{ github.ref }}' =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+((a|b|rc|post)[0-9]+)?(\.dev[0-9]+)?$ ]]; then
          echo 'match=false' >> $GITHUB_OUTPUT
          echo "wrong release tag format. see https://peps.python.org/pep-0440/";
          exit 1;
        fi;
        package_version=$(python3 ./setup.py --version)
        if [[ ${{ github.ref_name }} != "$package_version" ]]; then
          echo 'match=false' >> $GITHUB_OUTPUT
          echo "package version in setup.cfg and release tag do not match";
          exit 1;
        fi;
        echo 'match=true' >> $GITHUB_OUTPUT

    - name: Build
      if: steps.check_tag.outputs.match == 'true'
      run: |
        python -m build

    - name: Publish
      if: steps.check_tag.outputs.match == 'true'
      run:
        twine upload --repository-url=${{ secrets.PYPI_REGISTRY }} dist/*
